---
title: "Survey Analysis"
author: "Rocky Mazorow"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
header-includes:
   - \renewcommand{\arraystretch}{1.5}
   -  \usepackage{float}
   -  \floatplacement{figure}{H}
geometry: 
  - top=0.25in
  - bottom=0.25in
  - left=0.5in
  - right=0.5in
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(R.matlab)
library(readxl)
library(dplyr)
library(ggplot2)
library(ggh4x)
library(ggpubr)
library(cowplot)
library(scales)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
#                      fig.path = "r_images/",
#                      dev = c("pdf", "svg"),
                       fig.align = 'center')
```

```{r eqn, echo=FALSE}
#+++++++++++++++++++++++++
# Function to calculate the mean and the standard deviation
# for each group
#+++++++++++++++++++++++++
# data : a data frame
# varname : the name of a column containing the variable
#to be summarized
# groupnames : vector of column names to be used as
# grouping variables
data_summary <- function(data, varname, groupnames=''){
  require(plyr)
  summary_func <- function(x, col){
    c(n <- sum(!is.na( x[[col]] )),
    mean <- mean( x[[col]], na.rm=TRUE),
    sd <- sd( x[[col]], na.rm=TRUE),
    se <- sd / sqrt(n),
    ic <- se * qt((1-0.05)/2 + 0.5, n-1))
  }
  if (length(groupnames)==1 && groupnames=='') {
    col = which(colnames(data) == varname) 
    data_sum <- summary_func(data,col)
  }
  else {
    data_sum <- ddply(data, groupnames, .fun=summary_func, varname)
    data_sum <- rename(data_sum, c("V1" = "n", "V2" = "mean", "V3" = "sd", "V4" = "se", "V5" = "ic"))
  }
  return(data_sum)
}
```

```{r theme, echo=FALSE}
# Font size in mm for certain functions
f12 <- 4.233
mmPx <- f12/12
f8 <- mmPx*8

theme_RNM <- theme(panel.background = element_rect(fill = "white"), panel.border = element_blank(),
          legend.key = element_rect(fill = "transparent"), legend.position=c(0.5, 1), 
          legend.title = element_text(size = 10, face = "bold", color = "black", margin=margin(0,0.5,0,0, unit='cm')),
          legend.text = element_text(size = 10, color = "black"), legend.background = element_rect(fill='transparent'),
          legend.spacing.x = unit(0.8, 'cm'), legend.key.spacing.x = unit(0.3, 'cm'),
          legend.box.margin = margin(0, 10, 0, 10), legend.direction="horizontal", legend.box = "horizontal",
          #legend.box.background = element_rect(color="black", size=0.15),
          strip.text = element_text(size = 10), strip.placement = "outside", strip.background = element_blank(),
          plot.tag = element_text(size = 25, color = "black", face = "bold", hjust = 1),
          plot.title = element_text(size = 10, color = "black", face = "bold", hjust = 0.5),
          axis.title = element_text(size = 10, color = "black", face = "bold"), 
          axis.text = element_text(size = 10, color = "black"), 
          axis.line = element_line(color = "black"), axis.ticks = element_line(color = "black"),
          axis.ticks.length=unit(0.1,"inch"), axis.title.x = element_blank(), axis.text.x = element_blank(), 
          axis.line.x = element_blank(), axis.ticks.x = element_blank())  
```

```{r compile_surveys, echo = FALSE}
# read in .mat file
excel <- read_excel('SurveyScores.xlsx', na="NA")
Survey <-  as.data.frame(excel)
Survey$SubID <- factor(Survey$SubID)
Survey$Group <- sapply(strsplit(excel$SubID, '_'), function(x) x[1])
Survey$SubID <- factor(Survey$SubID)
Survey$Group <- factor(Survey$Group)
  

# Calculate group average for SUS
SUS <- data.frame(Group = Survey$Group, Score = Survey$SusAvg, Scale = rep("SUS", by = length(levels(Survey$SubID))))
data_sus <- data_summary(SUS, varname="Score", groupnames="Group")
data_sus$Scale <-rep("SUS", by = length(levels(Survey$Group)))


# Calculate group average for IMI subscales
IMI <- data.frame(Group = factor(),
                  Score=double(),
                  Scale=factor())
for (s in 1:length(Survey$SubID)) {
  i <- (s-1)*6 + 1
  Group <- rep(Survey$Group[s], by = 6)
  Score <- c(Survey$ImiInterest[s], Survey$ImiEffort[s], Survey$ImiValue[s], Survey$ImiCompetence[s], Survey$ImiChoice[s], (8 - Survey$ImiPressure[s]))
  Scale <- c('Enjoyment', 'Effort',  'Usefulness',  'Competence', 'Choice', 'Tension*')
  IMI <- rbind(IMI, data.frame(Group, Score,Scale))
}
IMI$Scale <- factor(IMI$Scale)
IMI$Scale <- ordered(IMI$Scale, levels = c('Enjoyment','Effort','Competence','Choice','Usefulness','Tension*'))
IMI$Group <- factor(IMI$Group)
data_IMI <- data_summary(IMI, varname="Score", groupnames=c("Group","Scale"))

# Calculate group average for QUEST subscales
QST <- data.frame(Group = factor(),
                  Score=double(),
                  Scale=factor())
for (s in 1:length(Survey$SubID)) {
  i <- (s-1)*6 + 1
  Group <- rep(Survey$Group[s], by = 6)
  Score <- c(Survey$QuestWeight[s], Survey$QuestSafety[s], Survey$QuestEase[s], Survey$QuestComfort[s], Survey$QuestEffect[s], Survey$QuestService[s], Survey$QuestAvg[s])
  Scale <- c('Weight', 'Safety',  'Ease of Use',  'Comfort', 'Effectiveness', 'Instructions', 'Average')
  QST <- rbind(QST, data.frame(Group, Score,Scale))
}
QST$Scale <- factor(QST$Scale)
QST$Group <- factor(QST$Group)
data_QST <- data_summary(QST, varname="Score", groupnames=c("Group","Scale"))

qItems <- data.frame(SubID = rep(Survey[[1]],3), 
                     Group = rep(Survey[[19]],3), 
                     Items=c(Survey[[16]], Survey[[17]], Survey[[18]]))
qItems$SubID <- as.factor(qItems$SubID)
qItems$Items <- as.factor(qItems$Items)
levels(qItems$Items) <- c("Comfort", "Ease of Use", "Effectiveness", "Instructions", "Safety", "Weight" )

```

\newpage

# Per Survey Results

## SUS

```{r plot_sus, echo = FALSE, fig.height=3, fig.width=6}
avgSUS <- data_summary(SUS, varname="Score", groupnames = c("Group","Scale"))
avgSUS$ci_min <- avgSUS$mean - avgSUS$ic
avgSUS$ci_max <- avgSUS$mean + avgSUS$ic
if (avgSUS$ci_min < 1) {
  avgSUS$ci_min <- 1
}
if (avgSUS$ci_max > 100) {
  avgSUS$ci_max <- 100
}

# Create ggplot2 barplot
sus_plot <- ggplot(avgSUS, aes(x = Scale, y = mean)) +
      geom_hline(yintercept = 68, linetype = "dashed", color = "black", linewidth = 0.25) +
      # Add individual subject points
      geom_dotplot(data = SUS, aes(x = Scale, y = Score), binaxis='y', stackdir='center',
               stackratio=1, dotsize=1.15, fill = "grey80", color = "grey80") +
      # Add error bars
      geom_errorbar(aes(ymin=ci_min, ymax=ci_max), width=0, linewidth=1, color = "forestgreen") +
      # Add mean data point and manually change symbol depending on group
      geom_point(size = 6, color = "forestgreen", shape = 95) +
      scale_y_continuous(name="survey scores", breaks=seq(0, 100, 20)) +
      labs(title="Usability\n(SUS)") + 
      guides(y=guide_axis_truncated(trunc_lower = 37, trunc_upper = 100)) + expand_limits(y = c(37,100))

sus_plot <- sus_plot + theme_RNM

print(avgSUS)
sus_plot
```

## IMI

```{r plot_imi, echo = FALSE, fig.height=3, fig.width=6}
avgIMI <- data_summary(IMI, varname="Score", groupnames = c("Group","Scale"))
avgIMI$ci_min <- avgIMI$mean - avgIMI$ic
avgIMI$ci_max <- avgIMI$mean + avgIMI$ic
for (s in 1:6) {
  if (avgIMI$ci_min[s] < 1) {
    avgIMI$ci_min[s] <- 1
  }
  if (avgIMI$ci_max[s] > 7) {
    avgIMI$ci_max[s] <- 7
  }
}

# Create ggplot2 barplot
imi_plot <- ggplot(avgIMI, aes(x = Scale, y = mean)) +
      geom_hline(yintercept = 4, linetype = "dashed", color = "black", linewidth = 0.25) +
      # Add individual subject points
      geom_dotplot(data = IMI, aes(x = Scale, y = Score), binaxis='y', stackdir='center',
               stackratio=1, dotsize=1.1, fill = "grey80", color = "grey80") +
      # Add error bars
      geom_errorbar(aes(ymin=ci_min, ymax=ci_max), width=0, linewidth=1, color = "forestgreen") +
      # Add mean data point and manually change symbol depending on group
      geom_point(size = 6, color = "forestgreen", shape = 95) +
      scale_y_continuous(name="survey scores", breaks=seq(1, 7, 1)) +
      labs(title="Intrinsic Motivation\n(IMI)") +
      guides(y = guide_axis_truncated(trunc_lower = 1, trunc_upper = 7)) + expand_limits(y = c(1,7))

imi_plot <- imi_plot + theme_RNM + theme(axis.text.x = element_text(angle = 40)) 

print(avgIMI)
imi_plot
```

## QUEST

```{r plot_qst_p1, echo = FALSE, fig.height=3, fig.width=6}
QST1 <- QST[which(QST$Scale=="Average"),]
avgQST <- data_summary(QST1, varname="Score", groupnames = c("Group","Scale"))
avgQST$ci_min <- avgQST$mean - avgQST$ic
avgQST$ci_max <- avgQST$mean + avgQST$ic
if (avgQST$ci_min < 1) {
  avgQST$ci_min <- 1
}
if (avgQST$ci_max > 5) {
  avgQST$ci_max <- 5
}

# Create ggplot2 barplot
qst_plot1 <- ggplot(avgQST, aes(x = Scale, y = mean)) +
      geom_hline(yintercept = 3, linetype = "dashed", color = "black", linewidth = 0.25) +
      # Add individual subject points
      geom_dotplot(data = QST1, aes(x = Scale, y = Score), binaxis='y', stackdir='center',
               stackratio=1, dotsize=0.75, fill = "grey80", color = "grey80") +
      # Add error bars
      geom_errorbar(aes(ymin=ci_min, ymax=ci_max), width=0, linewidth=1, color = "forestgreen") +
      # Add mean data point and manually change symbol depending on group
      geom_point(size = 6, color = "forestgreen", shape = 95) +
      scale_y_continuous(name="survey scores", breaks=seq(1, 5, 1)) +
      labs(title="Satisfaction\n(QUEST)") +
  guides(y=guide_axis_truncated(trunc_lower = 1, trunc_upper = 5)) + expand_limits(y = c(1,5))

qst_plot1 <- qst_plot1 + theme_RNM

print(avgQST)
qst_plot1
```

```{r plot_qst_p2_h, echo = FALSE, fig.height=3, fig.width=6}
palette <- hue_pal()(12)
col <- rev(palette[c(1,2,5,9,10,12)])

QST2 <- QST[which(QST$Scale!="Average"),]
subQST <- data_summary(QST2, varname="Score", groupnames = c("Group","Scale"))
subQST$ci_min <- subQST$mean - subQST$ic
subQST$ci_max <- subQST$mean + subQST$ic
for (s in 1:6) {
  if (subQST$ci_min[s] < 1) {
    subQST$ci_min[s] <- 1
  }
  if (subQST$ci_max[s] > 5) {
    subQST$ci_max[s] <- 5
  }
}
qst_summ <- table(qItems$Items)
qst_summ <- data.frame(Scale = names(qst_summ),
                       Frequency = as.numeric(qst_summ))
ordered <- qst_summ$Scale[order(qst_summ$Frequency, decreasing=FALSE)]
qst_summ$Scale <- factor(qst_summ$Scale, levels = ordered)
QST2$Scale <- factor(QST2$Scale, levels = ordered)
subQST$Scale <- factor(subQST$Scale, levels = ordered)

plot <- ggplot(subQST, aes(x = Scale, y = mean, color = Scale)) +
      geom_hline(yintercept = 3, linetype = "dashed", color = "black", linewidth = 0.25) +
      # Add individual subject points
      geom_dotplot(data = QST2, aes(x = Scale, y = Score), binaxis='y', stackdir='center',
               stackratio=1, dotsize=0.6, fill = "grey80", color = "grey80") +
      # Add error bars
      geom_errorbar(aes(ymin=ci_min, ymax=ci_max), width=0, linewidth=0.95) +
      # Add mean data point and manually change symbol depending on group
      geom_point(size = 6, shape = 108) +
      scale_y_continuous(name="items scores", breaks=seq(2, 5, 1)) +
      scale_x_discrete(name ="Scales", limits=levels(subQST$Scale)) +
      guides(x = guide_axis_truncated(trunc_lower = 1.9, trunc_upper = 5)) +
  expand_limits(y = c(1,5)) +
  theme(panel.background = element_rect(fill = "white"), panel.border = element_blank(),
        axis.line = element_line(color = "black"), axis.ticks = element_line(color = "black"),
        axis.ticks.length=unit(0.1,"inch"),
        axis.title.y = element_blank(), axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), axis.text.y = element_blank(),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 10, color = "black", face = "bold"),
        legend.position = "none") +
  scale_color_manual(values=col, guide="none") +
  coord_flip()

upper <- max(qst_summ$Frequency, na.rm=TRUE)
hist <- ggplot(qst_summ, aes(x = Scale, y = Frequency, fill = Scale)) +
  geom_bar(stat = "identity", width=0.65) +
  scale_y_continuous(breaks=seq(0, upper, 1)) + scale_y_reverse() +
  theme(panel.background = element_rect(fill = "white"), panel.border = element_blank(),
        axis.line = element_line(color = "black"), axis.ticks = element_line(color = "black"),
        axis.ticks.length=unit(0.1,"inch"),
        axis.title.y = element_blank(), axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), axis.text.y = element_blank(),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 10, color = "black", face = "bold"),
        legend.position = "none") +
  scale_fill_manual(values=col, guide="none") +
  guides(x=guide_axis_truncated(trunc_lower = 0, trunc_upper = upper+0.2)) +
  coord_flip() + labs(y="frequency")

qst_plot2 <-
  ggarrange(hist, plot, align="h", widths=c(0.6,1)) +
  labs(title = 'Ranked Satisfaction Items\n(QUEST)') +
  theme(plot.title = element_text(size = 10, color = "black", face = "bold", hjust = 0.5, vjust=0),
        plot.tag = element_text(size = 10, color = "black", face = "plain")) +
  draw_text(c("Instructions","Effectiveness","Comfort","Safety","Easy to Use","Weight"), 
            x = 0.5, y = seq(0.895, 0.315, by=-0.116), 
            size = 8, fontface = "bold", color = rev(col))

print(subQST)
qst_plot2
```


\newpage

# Combined Survey Results
```{r combined_survey_plot, echo=FALSE, fig.height=6, fig.width=6}
p1 <- ggarrange(sus_plot, NULL, imi_plot, align="h", ncol = 3, widths=c(1,0.2,3), labels = c("A","","B"))
p2 <- ggarrange(qst_plot1, NULL, qst_plot2, ncol = 3, widths=c(1,0.2,3), labels = c("C","","D"))
ggarrange(p1, p2, nrow = 2, font.label = list(size = 12, face = "bold"))

```

